// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXa82OmF7c-rSAlSfQvE22Gw01VlzLIF4',
    appId: '1:374660362861:web:bd38d3b01c966749e58564',
    messagingSenderId: '374660362861',
    projectId: 'ezoro-9a43e',
    authDomain: 'ezoro-9a43e.firebaseapp.com',
    storageBucket: 'ezoro-9a43e.firebasestorage.app',
    measurementId: 'G-B0LY2QJJVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlPZ2d07mS76RQi0Q2T1e9fQY-wldPI64',
    appId: '1:374660362861:android:db47b2f2664408f1e58564',
    messagingSenderId: '374660362861',
    projectId: 'ezoro-9a43e',
    storageBucket: 'ezoro-9a43e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6FHztqlEOByEOZb0u_ZoKkPw8U8KVRds',
    appId: '1:374660362861:ios:5b6bd7c78606bb25e58564',
    messagingSenderId: '374660362861',
    projectId: 'ezoro-9a43e',
    storageBucket: 'ezoro-9a43e.firebasestorage.app',
    iosClientId: '374660362861-6jnsces9nffh14it4ka2a2q9p08qj36s.apps.googleusercontent.com',
    iosBundleId: 'com.example.travelApp2',
  );
}
