import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:travel_app2/app/modules/notifications/controllers/notifications_controller.dart';
import 'package:travel_app2/app/services/api_service.dart';
import 'firebase_options.dart'; // Generated by FlutterFire

import 'app/constants/app_color.dart';
import 'app/routes/app_pages.dart';

// Background message handler
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("📩 BG Message: ${message.notification?.title} - ${message.notification?.body}");
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await GetStorage.init();
  Get.put(ApiService());
  Get.put(NotificationController());

  // Safe permission request
  try {
    FirebaseMessaging messaging = FirebaseMessaging.instance;

    NotificationSettings settings = await messaging.requestPermission(
      alert: true,
      badge: true,
      sound: true,
    );
    print('📌 Notification Permission: ${settings.authorizationStatus}');

    String? token = await messaging.getToken();
    print('📱 Device Token: $token');
  } catch (e) {
    print("⚠️ Notification permission error: $e");
  }

  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: AppColors.mainBg,
      ),
      initialRoute: Routes.SPLASH,
      getPages: AppPages.routes,
    );
  }
}
